- name: Create an empty file
  file:
    path: test_config_file.txt
    state: touch

- name: Write file content
  shell: echo "config_name = sample_value" > test_config_file.txt

- name: Change file permission
  file:
    path: test_config_file.txt
    mode: 0777
